[package]
name = "ftest"
version = "0.1.0"
edition = "2024"
authors = ["Fuji"]
description = "A set of declarative macros designed to simplify the declaration of unit tests and benchmarks in Rust"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["test", "testing", "unit-test", "benchmark", "utils"]
categories = ["development-tools::testing", "development-tools::profiling", "development-tools::procedural-macro"]
repository = "https://github.com/fuji-184/FTest"
homepage = "https://github.com/fuji-184/FTest"

[features]
bench= []
trace= []
tokio = ["dep:tokio"]

[dependencies]
anyhow = "1.0.102"
color-eyre = "0.6.5"
tokio = { version = "1.52.3", features = ["macros", "rt", "rt-multi-thread"], optional = true }
